// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const createMusic = `-- name: CreateMusic :exec
INSERT INTO musics (
  title, artist, link
) VALUES (
  $1, $2, $3
)
`

type CreateMusicParams struct {
	Title  string
	Artist string
	Link   string
}

func (q *Queries) CreateMusic(ctx context.Context, arg CreateMusicParams) error {
	_, err := q.db.Exec(ctx, createMusic, arg.Title, arg.Artist, arg.Link)
	return err
}

const deleteMusic = `-- name: DeleteMusic :exec
DELETE FROM musics
WHERE id = $1
`

func (q *Queries) DeleteMusic(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMusic, id)
	return err
}

const listMusics = `-- name: ListMusics :many
SELECT id, title, artist, link FROM musics
ORDER BY title
`

func (q *Queries) ListMusics(ctx context.Context) ([]Music, error) {
	rows, err := q.db.Query(ctx, listMusics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMusic = `-- name: UpdateMusic :exec
UPDATE musics 
  set title = $2,
  artist = $3,
  link = $4
WHERE
  id = $1
`

type UpdateMusicParams struct {
	ID     int64
	Title  string
	Artist string
	Link   string
}

func (q *Queries) UpdateMusic(ctx context.Context, arg UpdateMusicParams) error {
	_, err := q.db.Exec(ctx, updateMusic,
		arg.ID,
		arg.Title,
		arg.Artist,
		arg.Link,
	)
	return err
}
